import { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Premium iPhone 15 Pro Case",
    price: 29.99,
    description: "Premium protective case with MagSafe compatibility",
    category: "iPhone Cover",
    image: "https://images.unsplash.com/photo-1603313011101-320f26a4f6f6?w=500",
    features: [
      "Military-grade protection",
      "MagSafe compatible",
      "Slim profile design",
    ],
    specs: {
      material: "TPU + PC",
      compatibility: "iPhone 15 Pro",
      thickness: "2mm",
    },
  },
  {
    id: "2",
    name: "AirPods Pro Case",
    price: 24.99,
    description: "Protective silicone case for AirPods Pro",
    category: "Earphones/iPod",
    image: "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=500",
    features: [
      "Shock-proof design",
      "Wireless charging compatible",
      "Carabiner included",
    ],
    specs: {
      material: "Silicone",
      compatibility: "AirPods Pro 1st/2nd Gen",
      weight: "28g",
    },
  },
  {
    id: "3",
    name: 'MacBook Pro 16" Sleeve',
    price: 49.99,
    description: "Premium leather sleeve for MacBook Pro",
    category: "Laptop & iPad Cover",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500",
    features: [
      "Genuine leather",
      "Microfiber interior",
      "Additional accessories pocket",
    ],
    specs: {
      material: "Premium leather",
      compatibility: 'MacBook Pro 16"',
      dimensions: "38.3 x 26.2 cm",
    },
  },
  {
    id: "4",
    name: "Premium Over-Ear Headphones",
    price: 199.99,
    description: "High-fidelity wireless headphones with noise cancellation",
    category: "Headphones",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
    features: [
      "Active noise cancellation",
      "40-hour battery life",
      "Premium sound quality",
    ],
    specs: {
      driver: "40mm",
      bluetooth: "5.0",
      weight: "250g",
    },
  },
  {
    id: "5",
    name: "Apple Watch Ultra Screen Protector",
    price: 19.99,
    description: "Full coverage tempered glass protection",
    category: "Screen Glass",
    image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=500",
    features: [
      "Edge-to-edge protection",
      "9H hardness",
      "Anti-fingerprint coating",
    ],
    specs: {
      thickness: "0.33mm",
      hardness: "9H",
      compatibility: "Apple Watch Ultra",
    },
  },
  {
    id: "6",
    name: "Apple Watch Sport Band",
    price: 29.99,
    description: "High-performance fluoroelastomer band",
    category: "Watch",
    image: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=500",
    features: [
      "Sweat and water resistant",
      "Pin-and-tuck closure",
      "Multiple size options",
    ],
    specs: {
      material: "Fluoroelastomer",
      sizes: "S/M/L",
      compatibility: "All Apple Watch models",
    },
  },
  {
    id: "7",
    name: "iPad Pro Side Grip Case",
    price: 39.99,
    description: "Ergonomic side grip case with pencil holder",
    category: "Sides",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500",
    features: [
      "Apple Pencil holder",
      "Enhanced grip design",
      "Drop protection",
    ],
    specs: {
      material: "TPU + PC",
      compatibility: 'iPad Pro 12.9"',
      features: "Built-in stand",
    },
  },
  {
    id: "8",
    name: "TWS Earbuds",
    price: 89.99,
    description: "True wireless earbuds with active noise cancellation",
    category: "Earphones/iPod",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500",
    features: [
      "Active noise cancellation",
      "30-hour battery life",
      "Touch controls",
    ],
    specs: {
      driver: "12mm",
      bluetooth: "5.2",
      waterproof: "IPX4",
    },
  },
];

export const categories = [
  "All",
  "Earphones/iPod",
  "Headphones",
  "iPhone Cover",
  "Laptop & iPad Cover",
  "Screen Glass",
  "Sides",
  "Watch",
];

export const featuredProducts: Product[] = [
  {
    id: "1",
    name: "Premium iPhone 15 Pro Case",
    price: 29.99,
    description: "Premium protective case with MagSafe compatibility",
    category: "iPhone Cover",
    image: "https://images.unsplash.com/photo-1603313011101-320f26a4f6f6?w=500",
    features: [
      "Military-grade protection",
      "MagSafe compatible",
      "Slim profile design",
    ],
    specs: {
      material: "TPU + PC",
      compatibility: "iPhone 15 Pro",
      thickness: "2mm",
    },
  },
  {
    id: "4",
    name: "Premium Over-Ear Headphones",
    price: 199.99,
    description: "High-fidelity wireless headphones with noise cancellation",
    category: "Headphones",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
    features: [
      "Active noise cancellation",
      "40-hour battery life",
      "Premium sound quality",
    ],
    specs: {
      driver: "40mm",
      bluetooth: "5.0",
      weight: "250g",
    },
  },
  {
    id: "3",
    name: 'MacBook Pro 16" Sleeve',
    price: 49.99,
    description: "Premium leather sleeve for MacBook Pro",
    category: "Laptop & iPad Cover",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500",
    features: [
      "Genuine leather",
      "Microfiber interior",
      "Additional accessories pocket",
    ],
    specs: {
      material: "Premium leather",
      compatibility: 'MacBook Pro 16"',
      dimensions: "38.3 x 26.2 cm",
    },
  },
  {
    id: "8",
    name: "TWS Earbuds",
    price: 89.99,
    description: "True wireless earbuds with active noise cancellation",
    category: "Earphones/iPod",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500",
    features: [
      "Active noise cancellation",
      "30-hour battery life",
      "Touch controls",
    ],
    specs: {
      driver: "12mm",
      bluetooth: "5.2",
      waterproof: "IPX4",
    },
  },
  {
    id: "5",
    name: "Apple Watch Ultra Screen Protector",
    price: 19.99,
    description: "Full coverage tempered glass protection",
    category: "Screen Glass",
    image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=500",
    features: [
      "Edge-to-edge protection",
      "9H hardness",
      "Anti-fingerprint coating",
    ],
    specs: {
      thickness: "0.33mm",
      hardness: "9H",
      compatibility: "Apple Watch Ultra",
    },
  },
  {
    id: "6",
    name: "Apple Watch Sport Band",
    price: 29.99,
    description: "High-performance fluoroelastomer band",
    category: "Watch",
    image: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=500",
    features: [
      "Sweat and water resistant",
      "Pin-and-tuck closure",
      "Multiple size options",
    ],
    specs: {
      material: "Fluoroelastomer",
      sizes: "S/M/L",
      compatibility: "All Apple Watch models",
    },
  },
];
